### PR TITLE
 I added the menus

### PR DESCRIPTION
**Pull request by Bishersahloul**

### CODE REVIEW

**Comment by fannysoderlund** [comment]
Right now the program is asking the user to sign in 2 times, we need to change this. Need also more choices in the menus, for all our features. 

Customer menu

View your bookings
Make a booking
Edit your information
View your information
Edit one of your bookings
Search available bookings
Check Out

Employee menu

View list of customers
View list of rooms
View list of bookings
Edit customer
Edit room
Edit booking
Add customer
Add booking
Add room
Remove customer
Remove room
Remove booking
Check out a customer

Otherwise its nice! Just need it to work together with the sign in feature

**Comment by Bishersahloul** [comment]
do you mean we have to add switch statement for USER, I was thinking to do
that , but I added the method of menus in the try catch , please check it

**Comment by fannysoderlund** [comment]
Not really, I created a new branch called edits with the edits I meant

**Comment by Bishersahloul** [comment]
Thanks Fanny it is great . you added if statement for string.equals!!
does it work if make it parseInt
make it numbers
1 Employee
2Customer

**Pull request merged**
